### ISSUE TITLE
Double-click Error

### ISSUE THREAD

**Issue by mgroup81053** [tbflutter/Chess#4]
같은 기물을 여러 번 클릭했을 때, 기물의 종류에 따라 여러 부작용이 발생합니다.

- 백의 나이트 (2번 클릭): 공격 범위에 있는 기물을 전부 (피아 무관) 처치한 후 이동 가능한 칸(규칙 불명)으로 이동합니다.
- 백의 킹 (3번 클릭): 주변 기물(때때로 자기 자신 포함)을 삭제하고 이동합니다.
- 백의 룩 (2번 클릭): 게임 진행이 불가능해집니다.
- 백의 폰 (2번 클릭): 1칸 전진합니다.
- 기타 기물: 반응 없음

**Comment by hayuni7354** [comment]
```
MoveType findMoveType(List<int> posStart, List<int> posEnd) {
    if(posStart[0] <= -1 || posStart[0] >= boardSize[0] || posStart[1] <= -1 || posStart[1] >= boardSize[1]){
      return MoveType.x; // 보드 외부에 이동 시도
    }

    List<List<Pieces>> tempBoardState = boardState;
    Pieces startPiece = tempBoardState[posStart[1]][posStart[0]];
    Pieces endPiece = tempBoardState[posEnd[1]][posEnd[0]];

    print(boardState);
    tempBoardState[posEnd[1]][posEnd[0]] = startPiece;
    tempBoardState[posStart[1]][posStart[0]] = Pieces.nX;
    print(boardState);
// 이후 코드
```

print 앞뒤로 BoardState의 값이 달라지는 현상을 목격했습니다

**Comment by mgroup81053** [comment]
tempBoardState가 shallow-copied되어서 그런 것 같습니다. 이런 류의 변수는 deep-copy를 사용하지 않고 위와 같이 복사하면 한쪽만 수정해도 양쪽 모두 수정이 됩니다.

**Comment by hayuni7354** [comment]
수정해보았더니 폰, 나이트, 킹 이동은 이제 정상적으로 작동하는 듯 했지만,
일부 경우에 배열 인덱스를 잘못 참조하는 경우가 발생하여 게임 진행이 불가능해집니다.
비숍, 룩, 퀸은 여전히 이동히 불가능합니다.
![image](https://github.com/tbflutter/Chess/assets/154652943/a18cd618-0ea3-4e6d-99ce-fa1fed3db35c)

**Comment by hayuni7354** [comment]
1) 룩,비숍,퀸 이동에서 발생한 게임 진행 불가는 moveCalc()의 로직 오류인 것으로 보입니다.
2) 그 외의 이동에서 발생한 게임 진행 불가는 isChecked()의 로직 오류인 것으로 보입니다.
3) 앙파상이 불가능한 문제점은 moveCalc()의 로직 오류인 것으로 보입니다.

**Comment by hayuni7354** [comment]
앙파상, 룩, 비숍, 퀸 이동이 정상적으로 가능하도록 코드를 수정하였습니다.

**Comment by hayuni7354** [comment]
이동 및 체크 로직이 수정되어 작동될 것으로 보이나, 추가 테스트가 필요합니다.
